### ISSUE TITLE
The confirmation should be sent after name change and role assignment

### ISSUE THREAD

**Issue by hypha** [Cheukting/registration_desk#2]
https://github.com/Cheukting/registration_desk/blob/bd0dbb4154b070f2eed4dee65c474d35f2465f94/bot.py#L146-L148

This part should probably move down after the role assignment. In the rare case when name change results in a failure, we are still getting the confirmation that the user is successfully registered. One such case is that Discord restricts the nickname to <=32 characters. So if a user has a very long name, they would have got the message that they are successfully registered, but in fact they are not and cannot see any channels.

**Comment by Cheukting** [comment]
Done!
